import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
  display: "swap"
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
  display: "swap"
});
const mont = localFont({
  src: "./fonts/MontBold.woff",
  variable: "--font-mont",
  weight: "100 900",
  display: "swap"
});

export const metadata: Metadata = {
  title: "FBLA 2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${geistSans.variable} ${mont.variable} font-geist antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
